# [Numpy](https://www.youtube.com/watch?v=QUT1VHiLmmI)

Numpy is a multi-dimensional array library. You can use numpy to store data from 1D - $ \infty $. We prefer using NumPy arrays over lists because lists are significantly slower. Also Numpy use contigous memory

## Applications of Numpy

1. Replacement of matlab
2. plotting
3. Backend
4. Machine Learning

## IMPORTING LIBRARIES

In [2]:
import numpy as np

## The Basics

In [3]:
a = np.array([1,2,3,4], dtype = "int16") # pass a list inside the np.array()
print(a)
b = np.array([[1,2,3,4,5],[6,7.0,8.0,9.0, 10.0]]) # You can keep on nesting and nesting lists to get multi-dimensional arrays
print(b)

[1 2 3 4]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [4]:
### Getting the dimensions of the numpy array
print(a.ndim, b.ndim)

1 2


In [5]:
### Getting the shape - number of rows and columns
a.shape, b.shape

((4,), (2, 5))

In [6]:
# Getting type
a.dtype, b.dtype

(dtype('int16'), dtype('float64'))

In [7]:
# Getting size
print(a.itemsize, b.itemsize)
# Getting total size
a.nbytes

2 8


8

## MANIPULATING NUMPY ARRAYS

In [74]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a, a.shape)
print(a > 4)
a[a > 4] # returns the values 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] (2, 7)
[[False False False False  True  True  True]
 [ True  True  True  True  True  True  True]]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
## Getting a specific element [r,c]
a[1,4], a[-1, -3]

(12, 12)

In [10]:
## Getting a specific row/column
print(a[0,:], a[:, 2])

## More manipulation [startindex:endindex:stepsize] - end index is exclusive
a[0, 1:5:2]

[1 2 3 4 5 6 7] [ 3 10]


array([2, 4])

In [11]:
##  Updating a value in numpy array
print(a[1,5])
a[1,5] = 31
print(a[1,5])
print(a[:,2])
a[:, 2] = 6 # [1,2]
print(a[:,2])

13
31
[ 3 10]
[6 6]


## Initializing Different Types of Arrays

In [12]:
## All zeros matrix - specify shape (4), ((2,3)), ((2,3,2))
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [13]:
## All ones matrix
ones = np.ones((4,2,3), dtype = "int32")
ones, ones.shape

(array([[[1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1]]], dtype=int32),
 (4, 2, 3))

In [14]:
# custom value
full = np.full((2,2), 99)
full

array([[99, 99],
       [99, 99]])

In [15]:
# full-like - we can use this to take a shape that has already been built
np.full_like(full,4)

array([[4, 4],
       [4, 4]])

In [16]:
# Matrix of random numbers btw 0,1
np.random.rand(4,2)

array([[0.06124226, 0.37541682],
       [0.49430225, 0.40531683],
       [0.37928467, 0.9181848 ],
       [0.48727431, 0.46457533]])

In [17]:
# random int
np.random.randint(4,8,size=(3,3))

array([[5, 6, 6],
       [7, 4, 6],
       [5, 7, 7]])

In [18]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## NUMPY MATHEMATICS

Element wise calculation

In [19]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [30]:
# adding scalars = adds 2 to  every element in the array - ELEMENT WISE COMPUTATION
a + 2

array([3, 4, 5, 6])

In [22]:
# subtracts two from every element in the array
a - 2

array([-1,  0,  1,  2])

In [23]:
a * 2

array([2, 4, 6, 8])

In [24]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [25]:
b = np.array([1,0,1, 0])
a + b

array([2, 2, 4, 4])

In [26]:
a ** 2

array([ 1,  4,  9, 16])

In [28]:
# take sin of the value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## LINEAR ALGEBRA

1. determinant
2. Trace
3. Singular Value Decomposition (SVD)
4. EigenValues
5. Matrix Norm
6. Inverse

In [36]:
a = np.full((2,3), 23)
print(a)
b = np.full((3,2), 32)
print(b)
print(np.dot(a,b))
np.matmul(a,b)


[[23 23 23]
 [23 23 23]]
[[32 32]
 [32 32]
 [32 32]]
[[2208 2208]
 [2208 2208]]


array([[2208, 2208],
       [2208, 2208]])

In [43]:
c = np.identity(3)
# Finding the determinant
print(np.linalg.det(np.dot(a, b)))
np.linalg.det(c)

0.0


1.0

## Statistics

In [45]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
print(np.mean(stats))
print(np.mean(stats, axis=1)) # mean along the rows (1 is the y axis, the second dimension)
print(np.mean(stats, axis=0)) # mean along the columns (0 is the x axis, the first dimension)
np.mean(stats) # This one does the mean across the total elements

3.5
[2. 5.]
[2.5 3.5 4.5]


3.5

In [58]:
print(np.max(stats, axis = 1)) # along the y axis
print(np.max(stats, axis = 0)) # along the x axis
np.max(stats) # this one does the max across all elements in the array

[3 6]
[4 5 6]


6

In [59]:
print(np.sum(stats))

21


## REORGANIZING ARRAYS



In [62]:
before = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(before, before.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [66]:
# changing shape
after = before.reshape((10,1))
after, after.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 (10, 1))

In [69]:
# vertically stacking matrices and vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
np.vstack([v1, v2, v1])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [72]:
# Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1, h2]) # it adds the elements to the rows of the first h1

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## MISC

In [ ]:
## loading data from a file
# np.getnfromtxt('.txt', delimeter = ',') - comes as an array