# [Numpy](https://www.youtube.com/watch?v=QUT1VHiLmmI)

Numpy is a multi-dimensional array library. You can use numpy to store data from 1D - $ \infty $. We prefer using NumPy arrays over lists because lists are significantly slower. Also Numpy use contigous memory

## Applications of Numpy

1. Replacement of matlab
2. plotting
3. Backend
4. Machine Learning

## IMPORTING LIBRARIES

In [1]:
import numpy as np

## The Basics

In [14]:
a = np.array([1,2,3,4], dtype = "int16") # pass a list inside the np.array()
print(a)
b = np.array([[1,2,3,4,5],[6,7.0,8.0,9.0, 10.0]]) # You can keep on nesting and nesting lists to get multi-dimensional arrays
print(b)

[1 2 3 4]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [10]:
### Getting the dimensions of the numpy array
print(a.ndim, b.ndim)

1 2


In [12]:
### Getting the shape - number of rows and columns
a.shape, b.shape

((4,), (2, 5))

In [15]:
# Getting type
a.dtype, b.dtype

(dtype('int16'), dtype('float64'))

In [19]:
# Getting size
print(a.itemsize, b.itemsize)
# Getting total size
a.nbytes

2 8


8

## MANIPULATING NUMPY ARRAYS

In [22]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a, a.shape

(array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]),
 (2, 7))

In [24]:
## Getting a specific element [r,c]
a[1,4], a[-1, -3]

(12, 12)

In [31]:
## Getting a specific row/column
print(a[0,:], a[:, 2])

## More manipulation [startindex:endindex:stepsize] - end index is exclusive
a[0, 1:5:2]

[1 2 3 4 5 6 7] [ 3 10]


array([2, 4])

In [36]:
##  Updating a value in numpy array
print(a[1,5])
a[1,5] = 31
print(a[1,5])
print(a[:,2])
a[:, 2] = 6 # [1,2]
print(a[:,2])

31
31
[5 5]
[6 6]


## Initializing Different Types of Arrays

In [37]:
## All zeros matrix - specify shape (4), ((2,3)), ((2,3,2))
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [39]:
## All ones matrix
ones = np.ones((4,2,3))
ones, ones.shape

(array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]]),
 (4, 2, 3))