# [Numpy](https://www.youtube.com/watch?v=QUT1VHiLmmI)

Numpy is a multi-dimensional array library. You can use numpy to store data from 1D - $ \infty $. We prefer using NumPy arrays over lists because lists are significantly slower. Also Numpy use contigous memory

## Applications of Numpy

1. Replacement of matlab
2. plotting
3. Backend
4. Machine Learning

## IMPORTING LIBRARIES

In [1]:
import numpy as np

## The Basics

In [7]:
a = np.array([1,2,3,4]) # pass a list inside the np.array()
print(a)
b = np.array([[1,2,3,4,5],[6,7.0,8.0,9.0, 10.0]]) # You can keep on nesting and nesting lists to get multi-dimensional arrays
print(b)

[1 2 3 4]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


### Getting the dimensions of the numpy array

In [10]:
print(a.ndim, b.ndim)

1 2
