# [Numpy](https://www.youtube.com/watch?v=QUT1VHiLmmI)

Numpy is a multi-dimensional array library. You can use numpy to store data from 1D - $ \infty $. We prefer using NumPy arrays over lists because lists are significantly slower. Also Numpy use contigous memory

## Applications of Numpy

1. Replacement of matlab
2. plotting
3. Backend
4. Machine Learning

## IMPORTING LIBRARIES

In [2]:
import numpy as np

## The Basics

In [3]:
a = np.array([1,2,3,4], dtype = "int16") # pass a list inside the np.array()
print(a)
b = np.array([[1,2,3,4,5],[6,7.0,8.0,9.0, 10.0]]) # You can keep on nesting and nesting lists to get multi-dimensional arrays
print(b)

[1 2 3 4]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [4]:
### Getting the dimensions of the numpy array
print(a.ndim, b.ndim)

1 2


In [5]:
### Getting the shape - number of rows and columns
a.shape, b.shape

((4,), (2, 5))

In [6]:
# Getting type
a.dtype, b.dtype

(dtype('int16'), dtype('float64'))

In [7]:
# Getting size
print(a.itemsize, b.itemsize)
# Getting total size
a.nbytes

2 8


8

## MANIPULATING NUMPY ARRAYS

In [8]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a, a.shape

(array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]),
 (2, 7))

In [9]:
## Getting a specific element [r,c]
a[1,4], a[-1, -3]

(12, 12)

In [10]:
## Getting a specific row/column
print(a[0,:], a[:, 2])

## More manipulation [startindex:endindex:stepsize] - end index is exclusive
a[0, 1:5:2]

[1 2 3 4 5 6 7] [ 3 10]


array([2, 4])

In [11]:
##  Updating a value in numpy array
print(a[1,5])
a[1,5] = 31
print(a[1,5])
print(a[:,2])
a[:, 2] = 6 # [1,2]
print(a[:,2])

13
31
[ 3 10]
[6 6]


## Initializing Different Types of Arrays

In [12]:
## All zeros matrix - specify shape (4), ((2,3)), ((2,3,2))
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [13]:
## All ones matrix
ones = np.ones((4,2,3), dtype = "int32")
ones, ones.shape

(array([[[1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1]]], dtype=int32),
 (4, 2, 3))

In [16]:
# custom value
full = np.full((2,2), 99)
full

array([[99, 99],
       [99, 99]])

In [18]:
# full-like - we can use this to take a shape that has already been built
np.full_like(full,4)

array([[4, 4],
       [4, 4]])

In [22]:
# Matrix of random numbers btw 0,1
np.random.rand(4,2)

array([[0.66289803, 0.9216495 ],
       [0.18327904, 0.22046583],
       [0.63152141, 0.31315726],
       [0.6782151 , 0.34741334]])

In [28]:
# random int
np.random.randint(4,8,size=(3,3))

array([[6, 5, 4],
       [4, 5, 5],
       [7, 6, 6]])

In [29]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])