# Section I Linear Algebra


Learning linear algebra is crucial for you as students of machine learning for several reasons. First and foremost, linear algebra provides a fundamental understanding of the mathematical concepts underpinning various machine learning algorithms, enabling you to comprehend their inner workings and make informed decisions when selecting or modifying models. Matrix operations, such as multiplication, inversion, and decomposition, form the basis of many algorithms and optimizations in machine learning, making it essential for efficient computation and performance improvements. Moreover, linear algebra facilitates the manipulation and analysis of high-dimensional data, a common scenario in machine learning applications. By learning linear algebra, you gain the ability to perform tasks like dimensionality reduction, feature engineering, and data preprocessing with greater ease and effectiveness. Overall, mastering linear algebra empowers you as aspiring machine learning practitioners to approach complex problems with confidence and opens the door to a deeper understanding of advanced techniques and models in the field.

## 1.1 Vectors


Vectors play a crucial role in linear algebra and hold significant importance in machine learning. In linear algebra, vectors are fundamental objects used to represent points, directions, and transformations in vector spaces. They serve as building blocks for understanding vector operations, such as addition, scalar multiplication, and dot product, which are essential for solving systems of linear equations and finding eigenvalues and eigenvectors.

In machine learning, vectors are pervasive, representing features and data points in numerical form. They enable efficient storage and computation, allowing algorithms to handle large datasets effectively. Vector spaces are central to dimensionality reduction techniques like PCA and SVD, helping extract essential features and reduce noise. Moreover, similarity measures between vectors aid in clustering and classification tasks, and neural networks, fundamental to modern machine learning, heavily rely on vector-based operations for training and inference. Understanding vectors in linear algebra is, therefore, indispensable for mastering machine learning and developing cutting-edge applications.

### Row Vectors or Horizontal Vectors:
Row vectors are 1-dimensional arrays with shape (1, n), where 'n' is the number of elements in the vector. They are laid out in memory horizontally, and the data is accessed along the rows. To create a row vector in NumPy, you can use the numpy.array function or reshape a 1D array using numpy.reshape.

In [ ]:
import numpy as np

# Creating a row vector using numpy.array
row_vector = np.array([1, 2, 3])

# Creating a row vector using numpy.reshape
row_vector_reshaped = np.array([1, 2, 3]).reshape(1, -1)
print(f"vector : \n {row_vector}, shape {row_vector.shape}")
print(f"vector: \n {row_vector_reshaped}, shape {row_vector_reshaped.shape}")

vector : 
 [1 2 3], shape (3,)
vector: 
 [[1 2 3]], shape (1, 3)


### Column Vectors or Vertical Vectors:
Column vectors are also 1-dimensional arrays but with shape (n, 1). They are stored vertically in memory, and the data is accessed along the columns. Similarly, you can use the numpy.array function or reshape a 1D array to create a column vector.

In [ ]:
import numpy as np

# Creating a column vector using numpy.array
column_vector = np.array([1, 2, 3])

# Creating a column vector using numpy.reshape
column_vector_reshaped = np.array([1, 2, 3]).reshape(-1, 1)
print(f"vector:\n {column_vector}, shape {column_vector.shape}")
print(f"vector:\n {column_vector_reshaped}, shape {column_vector_reshaped.shape}")

vector:
 [1 2 3], shape (3,)
vector:
 [[1]
 [2]
 [3]], shape (3, 1)


### NB
vector: [1 2 3], shape (3,)
In this representation, vector is a 1-dimensional NumPy array with shape (3,). This is considered a 1D array or a rank-1 array in NumPy, and it represents a row vector with three elements: 1, 2, and 3. However, note that it is not explicitly a row vector in terms of linear algebra because it is not a 2D array.

vector: [[1 2 3]], shape (1, 3)
In this representation, vector is a 2-dimensional NumPy array with shape (1, 3). The double brackets signify that it's a 2D array with one row and three columns. This is a true row vector in terms of linear algebra because it has one row and multiple columns, which aligns with the definition of a row vector.

While both representations contain the same data, the difference lies in the shape of the array. The second representation explicitly captures the concept of a row vector with a shape of (1, 3), making it more suitable for linear algebra and certain mathematical operations. The first representation, although commonly used, is technically a 1D array with shape (3,) and requires special attention when performing certain operations to ensure correct behavior in linear algebra contexts.






## Operations with Vectors

### Vector Addition:
You can add two vectors element-wise using the + operator or the numpy.add() function.

In [ ]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result = vector1 + vector2
# Output: array([5, 7, 9])
result

array([5, 7, 9])

### Vector Subtraction:
You can subtract two vectors element-wise using the - operator or the numpy.subtract() function.

In [ ]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result = vector2 - vector1
# Output: array([3, 3, 3])
result

array([3, 3, 3])

### Examples with Column Vectors

In [ ]:
import numpy as np

vector1 = np.array([[1],
                    [2],
                    [3]])

vector2 = np.array([[4],
                    [5],
                    [6]])

result = vector1 + vector2
# Output:
# array([[5],
#        [7],
#        [9]])
print("Adding two column vectors")
result

import numpy as np

vector1 = np.array([[1],
                    [2],
                    [3]])

vector2 = np.array([[4],
                    [5],
                    [6]])

result = vector2 - vector1
# Output:
# array([[3],
#        [3],
#        [3]])
print('subtracting two column vectors')
result

Adding two column vectors
subtracting two column vectors


array([[3],
       [3],
       [3]])

### Numpy Broadcasting
You must be wondering what if you add a row vector and a column vector.
Broadcasting in NumPy is a powerful feature that allows element-wise operations between arrays with different shapes, making it possible to perform operations on arrays that would otherwise be incompatible due to their dimensions.

The broadcasting rules in NumPy are applied when performing element-wise operations (e.g., addition, subtraction, multiplication, division, etc.) between two arrays. The broadcasting process involves automatically aligning and extending the dimensions of smaller arrays to match the shape of larger arrays, so that the operation can be performed element-wise.

Broadcasting follows a set of rules to determine how arrays should be broadcasted:
<br>
If the arrays have the same shape, no broadcasting is needed, and the operation is performed element-wise as expected.
<br>
If the arrays have different shapes, NumPy compares their dimensions from right to left:
<br>
If the dimensions match or one of the arrays has a size of 1 in a particular dimension, they are compatible for broadcasting in that dimension.
<br>
If the dimensions don't match and none of the arrays has a size of 1 in a particular dimension, then broadcasting is not possible, and an error will be raised.
<br>
During broadcasting, NumPy replicates the array along the dimensions that have a size of 1, making them compatible with the other array. This process is done implicitly and efficiently, without actually creating multiple copies of the data in memory.

In [ ]:
import numpy as np

# Row vector (shape: (1, 3))
row_vector = np.array([[1, 2, 3]])

# Column vector (shape: (3, 1))
column_vector = np.array([[4],
                          [5],
                          [6]])

# Broadcasting occurs here when we add the row vector and column vector.
# The row vector is broadcasted to (3, 3), and the column vector is broadcasted to (3, 3).
# Broadcasting allows NumPy to expand the vectors along the appropriate axes to match their shapes.
result = row_vector + column_vector

# Output:
# array([[5, 6, 7],
#        [6, 7, 8],
#        [7, 8, 9]])
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### Element-wise Multiplication (Hadamard Product):
You can perform element-wise multiplication of two 1D vectors using the * operator or the numpy.multiply() function.

In [ ]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result = vector1 * vector2
# Output: array([4, 10, 18])
result

array([ 4, 10, 18])

### Element-wise Division:
You can perform element-wise division of two 1D vectors using the / operator or the numpy.divide() function.

In [ ]:
import numpy as np

vector1 = np.array([4, 8, 12])
vector2 = np.array([2, 2, 3])

result = vector1 / vector2
# Output: array([2., 4., 4.])
result

array([2., 4., 4.])

### Element-wise Exponentiation:
You can perform element-wise exponentiation of a 1D vector using the ** operator or the numpy.power() function.

In [ ]:
import numpy as np

vector = np.array([2, 3, 4])

result = vector ** 2
# Output: array([ 4,  9, 16])
result

array([ 4,  9, 16])

### Summation:
You can calculate the sum of all elements in a 1D vector using numpy.sum().

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

sum_result = np.sum(vector)
# Output: 15
sum_result

15

### Dot Product with Another 1D Vector:
You can calculate the dot product of two 1D vectors using numpy.dot() or the @ operator.
<br>
when performing the dot product (also known as inner product) between two vectors (1-dimensional arrays), there are specific constraints on the shape of the arrays to get a meaningful result. The dot product is a binary operation that takes two vectors and returns a scalar value.
<br>
The constraint for the dot product is that the two vectors must have the same length (number of elements). Mathematically, for two vectors a and b, both of shape (N,), the dot product a · b is defined only when N is the same for both a and b.

In [ ]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)  # or simply a.dot(b)

print(dot_product)  # Output: 32


32


### Cross product
the cross product is a binary operation performed on two 3-dimensional vectors (arrays with three elements each). The cross product between two vectors results in a new vector that is orthogonal (perpendicular) to the plane containing the original vectors.
<br>
The main constraint for performing the cross product in NumPy is that both vectors must be 1-dimensional arrays (vectors) of length 3. Mathematically, if a and b are two vectors with shapes (3,), the cross product a x b is well-defined.
<br>
#### Note
while numpy will allow the cross product between vectors in two dimensional space, the output does not make sense in the definition of dot product and hence you should rather add 0's in the missing direction

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cross_product = np.cross(a, b)

print(cross_product)  # Output: [-3  6 -3]


[-3  6 -3]


### Norm of a Vector:
You can calculate the norm (L2) (magnitude) of a vector using numpy.linalg.norm().

In [ ]:
import numpy as np

vector = np.array([3, 4])

norm = np.linalg.norm(vector)
# Output: 5.0
norm

5.0

#### These are just a few examples of vector operations in NumPy. The library provides a wide range of functions for vector manipulation and linear algebra operations, making it a powerful tool for various mathematical and machine learning tasks.

### The above operations by themself does not show the power of Numpy in solving mathematical problems. However, they form the basis of other complex operations hence understanding them will be beneficial for other linear algebraic operations